
    - name: Wait for parcels to be present
      wait_for:
        path: /opt/cloudera/parcels/CDH
        timeout: 600

    - service:
        name: cloudera-scm-agent
        state: stopped

    - service:
        name: cloudera-scm-agent
        state: started

    - name: Pause a few moments before applying template
      pause: 
        minutes: 2

    - name: Assign HostTemplate
      uri:
        url: "http://{{CMhost}}:{{CMport}}/api/v11/clusters/cluster/hostTemplates/{{template_name}}/commands/applyHostTemplate"
        method: POST
        user: "{{username}}" 
        password: "{{password}}"
        body_format: json
        headers:
          Content-Type: application/json
        body: '{"items": ["{{ hostname }}"] }'
      register: apply_template
